### ISSUE TITLE
Alert!!!!!!!!!!!!!!!!!!!1

### ISSUE THREAD

**Issue by SubhojeetDas1107** [Souvik2376/Mood-Detection-Final#2]
Very bad project, bikash nigga didnt like it, change the dataset and do it again bsdk!!!!!

**Comment by Souvik2376** [comment]
Man behind all thing 

<img width="271" alt="image" src="https://github.com/Souvik2376/Mood-Detection-Final/assets/100219950/155d6efd-7fce-4ece-925e-3a34b3e50f1f">

**Comment by SubhojeetDas1107** [comment]
hiye gache bc
